# FROM node:18.14.2-buster AS base
FROM node:20-buster AS base

RUN apt update && apt upgrade -y && \
  apt install gcc g++ make python git libc6-dev build-essential libpng-dev \
  libjpeg-dev libvips-dev libvips musl-dev node-gyp pngquant webp -y

RUN npm install -g gatsby-cli@5.14.0
EXPOSE 8000
