# FROM node:12.22.12-buster AS base
FROM node:12-buster AS base

RUN apt update && apt upgrade -y && \
  apt install gcc g++ make python git libc6-dev build-essential libpng-dev \
  libjpeg-dev libvips-dev libvips musl-dev node-gyp pngquant webp -y

RUN npm install -g gatsby-cli@2.19.2
EXPOSE 8000
