# FROM node:16.14.2-buster AS base
FROM node:14-slim AS base

RUN apt update && apt upgrade -y && \
  apt install gcc g++ make python git libc6-dev build-essential libpng-dev \
  libjpeg-dev libvips-dev libvips musl-dev node-gyp pngquant webp -y

RUN npm install -g gatsby-cli@3.15.0
EXPOSE 8000
