services:
  gatsby-cli-v3:
    container_name: gatsby-cli-v3-node14
    image: weaponsforge/gatsby-cli:v3-node14
    build:
      dockerfile: Dockerfile.v3
      target: base
    volumes:
      - /opt/app/node_modules
    stdin_open: true
    tty: true
