services:
  gatsby-cli-v4-18x:
    container_name: gatsby-cli-v4-18x
    image: weaponsforge/gatsby-cli-v4-18x:v18
    build:
      dockerfile: Dockerfile.v4.slim # Also try Dockerfile.v4.buster for complete image
      target: base
    volumes:
      - /opt/app/node_modules
    stdin_open: true
    tty: true
