FROM node:16-buster AS base

RUN apt update && apt upgrade -y && \
  apt install gcc g++ make python git libc6-dev build-essential libpng-dev \
  libjpeg-dev libvips-dev libvips musl-dev node-gyp pngquant webp -y

RUN npm install -g gatsby-cli@4.25.0
