name: Publish to Docker Hub

on:
  release:
    types: [published]

jobs:
  docker-build-push-v2:
    name: Build/Push v2 Image
    if: github.event.release.target_commitish == 'main' && vars.DOCKERHUB_USERNAME != ''
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build Images
        run: cd v2 && docker compose -f docker-compose.v2.yml build

      - name: Push Images to Docker Hub
        run: cd v2 && docker compose -f docker-compose.v2.yml push

  docker-build-push-v3:
    name: Build/Push v3 Image
    if: github.event.release.target_commitish == 'main' && vars.DOCKERHUB_USERNAME != ''
    runs-on: ubuntu-latest
    needs: docker-build-push-v2
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build Images
        run: cd v3 && docker compose -f docker-compose.v3.14x.yml build

      - name: Push Images to Docker Hub
        run: cd v3 && docker compose -f docker-compose.v3.14x.yml push

  docker-build-push-v4:
    name: Build/Push v4 Image
    if: github.event.release.target_commitish == 'main' && vars.DOCKERHUB_USERNAME != ''
    runs-on: ubuntu-latest
    needs: docker-build-push-v3
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build Images
        run: |
          cd v4 && docker compose -f docker-compose.v4.16x.yml build
          docker compose -f docker-compose.v4.18x.yml build

      - name: Push Images to Docker Hub
        run: |
          cd v4 && docker compose -f docker-compose.v4.16x.yml push
          docker compose -f docker-compose.v4.18x.yml push

  docker-build-push-v5:
    name: Build/Push v5 Image
    if: github.event.release.target_commitish == 'main' && vars.DOCKERHUB_USERNAME != ''
    runs-on: ubuntu-latest
    needs: docker-build-push-v4
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build Images
        run: |
          cd v5 && docker compose -f docker-compose.v5.18x.yml build
          docker compose -f docker-compose.v5.20x.yml build

      - name: Push Images to Docker Hub
        run: |
          cd v5 && docker compose -f docker-compose.v5.18x.yml push
          docker compose -f docker-compose.v5.20x.yml push
