name: Publish to Docker Hub

on:
  release:
    types: [published]
  push:
    branches-ignore:
      - 'main'

jobs:
  docker-build-push:
    name: Push Image Tags
    # if: github.event.release.target_commitish == 'main' && vars.DOCKERHUB_USERNAME != ''
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build Images
        run: |
          cd v2 && docker compose -f docker-compose.v2.yml build
          cd .. && cd v3 && docker compose -f docker-compose.v3.14x.yml build
          cd .. && cd v4 && docker compose -f docker-compose.v4.16x.yml build
          docker compose -f docker-compose.v4.18x.yml build
          cd .. && cd v5 && docker compose -f docker-compose.v5.18x.yml build
          docker compose -f docker-compose.v5.20x.yml build
          cd ..

      - name: Push Images to Docker Hub
        run: |
          cd v2 && docker compose -f docker-compose.v2.yml push
          cd .. && cd v3 && docker compose -f docker-compose.v3.14x.yml push
          cd .. && cd v4 && docker compose -f docker-compose.v4.16x.yml push
          docker compose -f docker-compose.v4.18x.yml push
          cd .. && cd v5 && docker compose -f docker-compose.v5.18x.yml push
          docker compose -f docker-compose.v5.20x.yml push
